import React, { useState } from 'react';
import './Services.css';

const Services = () => {
  const [expandedCard, setExpandedCard] = useState(null);

  const toggleReadMore = (index) => {
    setExpandedCard(expandedCard === index ? null : index);
  };

  const servicesData = [
    {
      icon: "📊",
      title: "ERP & Value-Added Solutions",
      fullContent: `<strong >Elevating ERP to Deliver Real Business Value</strong>

From SAP to other leading ERP platforms, we enhance, optimize, and transform systems into engines of intelligence, automation, and measurable outcomes.
We specialize in ERP enhancement and value-added solutions...

<b>Our Core Focus</b>
SAP Value-Added Solutions
• Process Optimization: Streamlining workflows with SAP modules and custom enhancements.
• Integration Services: Connecting SAP with third-party applications...
• Automation & Intelligence: Embedding AI, RPA...
• Custom Development: ABAP, Fiori, RAP...
• Performance Tuning: Ensuring speed, reliability...

<b>Other ERP Platforms</b>
• Microsoft Dynamics, Oracle NetSuite...
• Cross-ERP Analytics...
• Migration & Modernization...

<b>Why Choose Us</b>
• ERP Enhancement Experts...
• SAP Specialists...
• Multi-ERP Capability...
• Outcome-Driven Approach...

Ready to unlock more from your ERP? Let’s transform your systems into engines of growth.`
    },
    // ... (keep the other 3 services same as before)
    {
      icon: "🔄",
      title: "Digital Transformation with Full Stack Innovation",
      fullContent: `Empowering enterprises to thrive in the digital era...

<b>Why Digital Transformation Matters</b>
Organizations today face the challenge...

Our Full-Stack Technology Expertise
• Front-End Excellence: React, Angular...
• Back-End Power: Node.js, Python...
• Cloud & DevOps: Kubernetes, Docker...
• Data & AI: Big Data, Generative AI...
• Cybersecurity: Zero Trust...
• ERP & Enterprise Systems...
• Mobile & Edge...

<b>Business Impact</b>
• Agility...
• Innovation...
• Resilience...
• Scalability...`
    },
    // Add the remaining two services similarly with proper \n and • bullets
    {
      icon: "☁️",
      title: "Cloud Migration & Modernization",
      fullContent: `Accelerating enterprise growth...
Why Cloud Migration Matters
Legacy systems often limit agility...

<b>Our Cloud Expertise</b>
• Cloud Migration: Lift-and-shift...
• Multi-Cloud & Hybrid...
• Modernization...
• Data & AI in Cloud...
• Security & Compliance...
• ERP in Cloud...
• DevOps & Automation...

<b>Business Impact</b>
• Agility...
• Innovation...
• Resilience...
• Cost Optimization...`
    },
    {
      icon: "📈",
      title: "Enterprise Analytics & Insights",
      fullContent: `Turning data into decisions...

<b>Why Analytics Matters</b>
Data is the new currency...

<b>Our Analytics Expertise</b>
• Business Intelligence (BI): Power BI...
• Advanced Analytics...
• Big Data Platforms...
• Real-Time Analytics...
• Data Warehousing...
• ERP & Enterprise Data...
• Data Governance & Security...

<b>Business Impact</b>
• Smarter Decisions...
• Efficiency...
• Agility...
• Growth...`
    }
  ];

  return (
    <section className="section services">
      <div className="container">
        <h1 className="formheader">Services Offering</h1>
        
        <div className="services-grid">
          {servicesData.map((service, index) => (
            <div className="service-card" key={index}>
              <div className="icon-circle">
                <span>{service.icon}</span>
              </div>
              <h3>{service.title}</h3>

              <div 
                className={`service-description ${expandedCard === index ? 'expanded' : ''}`}
                dangerouslySetInnerHTML={{ 
                  __html: service.fullContent.replace(/\n/g, '<br>') 
                }}
              />

              <a
                href="readmore"
                className="read-more"
                onClick={(e) => {
                  e.preventDefault();
                  toggleReadMore(index);
                }}
              >
                {expandedCard === index ? 'Read Less ▲' : 'Read More ▼'}
              </a>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
};

export default Services;